services:
  devcontainer:
    image: quay.io/jupyter/datascience-notebook:2024-05-27
    container_name: notebook
    ports:
      - 8888:8888
    volumes:
      - ../../:/workspace:cached
      - ../:/home/jovyan/project
    tty: true
    stdin_open: true

  neo4j:
    container_name: neo4j
    image: neo4j:enterprise
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/llm-agents
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_apoc_import_file_use__neo4j__config: true
      NEO4J_PLUGINS: '["graph-data-science","apoc", "apoc-extended"]'
    volumes:
      - ../docker/neo4j/data:/data
      - ../docker/neo4j/logs:/logs
      - ../docker/neo4j/import:/var/lib/neo4j/import
      - ../docker/neo4j/plugins:/plugins